# This should be re-enabled when ./test/commands/update.test.ts is updated to not use AWS.
# name: Node.js CI

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   build:
#     runs-on: windows-latest
#     strategy:
#       matrix:
#         node-version: [14.x, 12.x]
#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}
#       - run: yarn install
#         env:
#           CI: true
#       - run: yarn test
#         env:
#           CI: true
